### ISSUE TITLE
Animations won't work

### ISSUE THREAD

**Issue by growthlabs** [gabergg/react-scrollable-anchor#3] opened 2017-03-25 03:39 UTC
Hello, so I'm trying to use the simplest possible example but it won't work. 
My link looks like this:  

`<a href="#step4">SGo to section 4</a> 
`
My component looks like this:

`       < ScrollableAnchor id={"step4"}>
                    <div>Ipsum Lorem Ipsum</div>
                    </ScrollableAnchor>`

So this triggers the jump to the div id but no animation happens at all even if I for example set the scrollDuration to 1000. 

My component is a modal so might this cause some issues?

Thanks!

**Comment by gabergg** [comment] 2017-03-28 17:44
I don't see anything wrong with that setup. It's might be caused by the fact that your component is a modal. Could you share a larger snippet that includes the modal and its container? Or at least the basic structure of your component(s)?

**Comment by gabergg** [comment] 2017-04-01 00:39
I imagine this is a duplicate of https://github.com/gabergg/react-scrollable-anchor/issues/4 given that you're using a modal. The code above looks fine, and I don't have any more context. We can re-open if that isn't the case.

**Closed by gabergg** 2017-04-01 00:39 UTC
Labels: duplicate
